# .github/workflows/frontend_ci.yml
name: Frontend CI — build on dev/PR, push on main (if secrets)

on:
  workflow_dispatch:
  push:
    branches: [ dev, main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

permissions:
  contents: read
  id-token: write

concurrency:
  group: frontend-ci-${{ github.ref }}
  cancel-in-progress: true

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  # Dev/PR: verify Docker image builds (no Azure, no push)
  build_frontend_locally:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker build (no push)
        run: |
          docker build -t local/frontend:${{ env.IMAGE_TAG }} ./frontend

  # Main: build & push to ACR (only if secrets exist)
  build_and_push_image:
    if: >
      needs.build_frontend_locally.result == 'success' &&
      github.ref == 'refs/heads/main' &&
      env.ACR_NAME != '' &&
      env.ACR_LOGIN_SERVER != ''
    runs-on: ubuntu-latest
    needs: build_frontend_locally
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name "${{ env.ACR_NAME }}"

      - name: Docker build & push
        run: |
          docker build -t "${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}" ./frontend
          docker tag  "${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}" "${{ env.ACR_LOGIN_SERVER }}/frontend:latest"
          docker push "${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}"
          docker push "${{ env.ACR_LOGIN_SERVER }}/frontend:latest"

      - name: Azure Logout
        if: always()
        run: az logout
